server:
    port: 8775
spring:
    application:
        name: cloud-zuul

# Eureka集群配置信息
eureka:
    instance:
        prefer-ip-address: true
        instance-id: ${spring.cloud.client.ip-address}:${server.port}
        lease-renewal-interval-in-seconds: 5
        lease-expiration-duration-in-seconds: 10
    client:
        serviceUrl:
            defaultZone: http://127.0.0.1:8761/eureka/

zuul:
    host:
        connect-timeout-millis: 10000
        socket-timeout-millis: 60000
    routes:
        server-auth:
            sensitiveHeaders:
        cloud-order-server:
            path: /cloud-order-server/**
            sensitiveHeaders:
            serviceId: cloud-order-server

security:
    oauth2:
        resource:
            user-info-uri:  http://server-auth/user
            prefer-token-info: false
            loadBalanced: true

####超时配置####
ribbon:
    ReadTimeout: 10000
    ConnectTimeout: 10000
    MaxAutoRetries: 1
    MaxAutoRetriesNextServer: 2
    eureka:
        enabled: true
hystrix:
    command:
        default:
            execution:
                timeout:
                    enabled: true
                isolation:
                    thread:
                        timeoutInMilliseconds: 600000
###超时配置###


